### ISSUE TITLE
[IP~] Probably should avoid hardcoded Values

### ISSUE THREAD

**Issue by theSoberSobber** [Akhilendra01/Machine-Learning-Labs#1]
Maybe use something like this for inferring headers
```py
def parse_dat_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    return lines.index('@data\n')
```

**Comment by Akhilendra01** [comment]
Thanks for the suggestion.
I was also thinking of removing the hardcoded header values for each file. But due to rush of submitting the assignment on time I was in hurry to complete it asap. Therefore, I went ahead with the hardcoded header values at that moment with the thought of fixing this in future.
I will fix this issue soon.

**Comment by Akhilendra01** [comment]
The issue has been fixed.
